### ISSUE TITLE
setAbsorption() passed a float when attacking a player wearing armour

### ISSUE THREAD

**Issue by Driesboy** [ClearSkyTeam/PocketMine-MP#87] opened 2017-07-13 08:36 UTC
### Issue description

https://github.com/pmmp/PocketMine-MP/issues/1071 and sometimes the server crash https://crash.pmmp.io/view/1096

### Steps to reproduce the issue

1. ...https://github.com/pmmp/PocketMine-MP/issues/1071
2. ...

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/issues/1071
* PHP: https://github.com/pmmp/PocketMine-MP/issues/1071
* Server OS: https://github.com/pmmp/PocketMine-MP/issues/1071

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...

**Comment by thebigsmileXD** [comment] 2017-07-13 09:26
Duplicate of https://github.com/pmmp/PocketMine-MP/issues/1071
Will mark as duplicate and wait for a proper fix instead of messing around.

> I'm going to mark this Fixed and Pending since this issue is resolved on api3/blocks, but the changes required to properly fix this in master without causing more bugs are extensive and I don't have any taste for doing the same job twice.

**Comment by Driesboy** [comment] 2017-07-13 09:35
but it kills my server every 20 min

**Comment by thebigsmileXD** [comment] 2017-07-13 10:10
Of the crash:
> Entity__64bit.php

There is no such file since ages.

**Comment by Driesboy** [comment] 2017-07-13 10:16
idk i compiled it with github desktop on mac

**Closed** 2017-07-13 10:47 UTC
Labels: #blamedktapps, bug, duplicate
